// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtuuDPN045FOpt7vfhPwMw_za0BiVxXA',
    appId: '1:917020258290:web:7bcdf21c59a6d64fe2c56b',
    messagingSenderId: '917020258290',
    projectId: 'purity---microcontroller',
    authDomain: 'purity---microcontroller.firebaseapp.com',
    storageBucket: 'purity---microcontroller.appspot.com',
    measurementId: 'G-N0ZYGT607E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe5lR2Qr4_Qz2U3HNQs_pEOEk5hTiOhTs',
    appId: '1:917020258290:android:1a951d7f40834c5ce2c56b',
    messagingSenderId: '917020258290',
    projectId: 'purity---microcontroller',
    storageBucket: 'purity---microcontroller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3JbQnjSvN3mhbFUiKY5cKXvfn_PQEHI',
    appId: '1:917020258290:ios:9b5f81f0188b5c49e2c56b',
    messagingSenderId: '917020258290',
    projectId: 'purity---microcontroller',
    storageBucket: 'purity---microcontroller.appspot.com',
    iosClientId: '917020258290-d4rj46r0ticm93gbj2dbq21lh4vb898e.apps.googleusercontent.com',
    iosBundleId: 'com.example.purity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3JbQnjSvN3mhbFUiKY5cKXvfn_PQEHI',
    appId: '1:917020258290:ios:9b5f81f0188b5c49e2c56b',
    messagingSenderId: '917020258290',
    projectId: 'purity---microcontroller',
    storageBucket: 'purity---microcontroller.appspot.com',
    iosClientId: '917020258290-d4rj46r0ticm93gbj2dbq21lh4vb898e.apps.googleusercontent.com',
    iosBundleId: 'com.example.purity',
  );
}
